# Generated by Django 4.2.27 on 2026-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('isRole', models.BooleanField(default=False, verbose_name='Active')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='roles.roles', verbose_name='Parent Roles')),
            ],
        ),
    ]
