# Generated by Django 4.2.27 on 2026-01-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission_type', '0001_initial'),
        ('roles', '0001_initial'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_permission', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission_type.permissiontype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.roles')),
            ],
            options={
                'unique_together': {('role', 'menu', 'permission_type')},
            },
        ),
    ]
